
openapi: "3.0.2"
info:
  version: 1.0.0
  title: Warehouse API
  license:
    name: MIT
paths:
  /v1/articles:
    get:
      tags:
        - Article
      summary: Retrieves all articles in the warehouse
      operationId: getArticles
      responses:
        '200':
          description: Returns all Articles in the warehouse
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
  /v1/article:
    put:
      tags:
        - Article
      summary: Adds a new article into the warehouse
      operationId: saveArticle
      requestBody:
        description: Article to be saved
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        '200':
          description: Returns all Articles in the warehouse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        404:
          description: Article not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

components:
  schemas:

    Article:
      type: object
      required:
        - name
        - stock
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        stock:
          type: integer
          format: int64

    ErrorObject:
      type: object
      required:
        - code
        - message
      properties:
        statusCode:
          type: integer
          format: int32
        message:
          type: string
