
openapi: "3.0.2"
info:
  version: 1.0.0
  title: Warehouse API
  license:
    name: MIT
paths:
  /v1/articles:
    get:
      tags:
        - Article
      summary: Retrieves all Articles in the warehouse
      operationId: getArticles
      responses:
        '200':
          description: Returns all Articles in the warehouse
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
  /v1/products:
    get:
      tags:
        - Product
      summary: Retrieves all Products in the warehouse
      operationId: getProducts
      responses:
        '200':
          description: Returns all Products in the warehouse
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

  /v1/products/sell:
    post:
      tags:
        - Product
      summary: Requests the sale of a product if there is inventory available
      operationId: sellProduct
      requestBody:
        description: Sale Request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SellRequest"
      responses:
        '200':
          description: Sale Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SellRequest"

components:
  schemas:

    Article:
      type: object
      required:
        - id
        - name
        - stock
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        stock:
          type: integer
          format: int32

    Product:
      type: object
      required:
        - id
        - name
        - price
        - containArticles
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: double
        quantityAvailable:
          type: integer
          format: int32
        containArticles:
          type: array
          items:
            $ref: "#/components/schemas/ContainArticles"

    ContainArticles:
      type: object
      required:
        - articleId
        - amount
      properties:
        articleId:
          type: integer
          format: int64
        amount:
          type: integer
          format: int32

    SellRequest:
      type: object
      required:
        - productId
        - quanityRequested
      properties:
        productId:
          type: integer
          format: int64
        quanityRequested:
          type: integer
          format: int32

    ErrorObject:
      type: object
      required:
        - code
        - message
      properties:
        statusCode:
          type: integer
          format: int32
        message:
          type: string
